In [168]:
!pip install -U fortran-magic
%reload_ext fortranmagic
%matplotlib inline
%load_ext fortranmagic

import sys; sys.path.append('..')

import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

mpl.rc('figure', figsize=(12, 7))

ran_the_first_cell = True

jan2017 = pd.to_datetime(['2017-01-03 00:00:00+00:00',
 '2017-01-04 00:00:00+00:00',
 '2017-01-05 00:00:00+00:00',
 '2017-01-06 00:00:00+00:00',
 '2017-01-09 00:00:00+00:00',
 '2017-01-10 00:00:00+00:00',
 '2017-01-11 00:00:00+00:00',
 '2017-01-12 00:00:00+00:00',
 '2017-01-13 00:00:00+00:00',
 '2017-01-17 00:00:00+00:00',
 '2017-01-18 00:00:00+00:00',
 '2017-01-19 00:00:00+00:00',
 '2017-01-20 00:00:00+00:00',
 '2017-01-23 00:00:00+00:00',
 '2017-01-24 00:00:00+00:00',
 '2017-01-25 00:00:00+00:00',
 '2017-01-26 00:00:00+00:00',
 '2017-01-27 00:00:00+00:00',
 '2017-01-30 00:00:00+00:00',
 '2017-01-31 00:00:00+00:00',
 '2017-02-01 00:00:00+00:00'])
calendar = jan2017.values.astype('datetime64[D]')

event_dates = pd.to_datetime(['2017-01-06 00:00:00+00:00', 
                             '2017-01-07 00:00:00+00:00', 
                             '2017-01-08 00:00:00+00:00']).values.astype('datetime64[D]')
event_values = np.array([10, 15, 20])

/usr/local/lib/python3.7/dist-packages/fortranmagic.py:147: UserWarning: get_ipython_cache_dir has moved to the IPython.paths module since IPython 4.0.
  self._lib_dir = os.path.join(get_ipython_cache_dir(), 'fortran')


The fortranmagic extension is already loaded. To reload it, use:
  %reload_ext fortranmagic


<center>
  <h1>The PyData Toolbox</h1>
  <h3>Scott Sanderson (Twitter: @scottbsanderson, GitHub: ssanderson)</h3>
  <h3><a href="https://github.com/ssanderson/pydata-toolbox">https://github.com/ssanderson/pydata-toolbox</a></h3>
</center>

# About Me:

<img src="images/me.jpg" alt="Drawing" style="width: 300px;"/>

- Senior Engineer at [Quantopian](www.quantopian.com)
- Background in Mathematics and Philosophy
- **Twitter:** [@scottbsanderson](https://twitter.com/scottbsanderson)
- **GitHub:** [ssanderson](github.com/ssanderson)

## Outline

- Built-in Data Structures
- Numpy `array`
- Pandas `Series`/`DataFrame`
- Plotting and "Real-World" Analyses

# Data Structures

> Rule 5. Data dominates. If you've chosen the right data structures and organized things well, the algorithms
will almost always be self-evident. Data structures, not algorithms, are central to programming.

- *Notes on Programming in C*, by Rob Pike.

# Lists

In [15]:

assert ran_the_first_cell, "Oh noes!"

In [16]:
l = [1, 'two', 3.0, 4, 5.0, "six"]
l

[1, 'two', 3.0, 4, 5.0, 'six']

mi ejemplo 01

In [17]:
s = ["string=","hola","entero=",1, "numero punto flotante=", 2.333]
s

['string=', 'hola', 'entero=', 1, 'numero punto flotante=', 2.333]

In [18]:
# Lists can be indexed like C-style arrays.
first = l[0]
second = l[1]
print("first:", first)
print("second:", second)

first: 1
second: two


mi ejemplo 02

In [19]:
elemento1 = s[0]
elemento2 = s[1]
print("elemento 1", elemento1)
print("elemento 2", elemento2)

elemento 1 string=
elemento 2 hola


In [20]:
# Negative indexing gives elements relative to the end of the list.
last = l[-1]
penultimate = l[-2]
print("last:", last)
print("second to last:", penultimate)

last: six
second to last: 5.0


mi ejemplo 03

In [21]:
ultimo=s[-1]
penultimo=s[-2]
print("último elemento=", ultimo)
print("penúltimo elemento=", penultimo)

último elemento= 2.333
penúltimo elemento= numero punto flotante=


In [22]:
# Lists can also be sliced, which makes a copy of elements between 
# start (inclusive) and stop (exclusive)
sublist = l[1:3]
sublist

['two', 3.0]

mi ejemplo 04

In [23]:
sublista=s[0:4]
sublista

['string=', 'hola', 'entero=', 1]

In [24]:
# l[:N] is equivalent to l[0:N].
first_three = l[:3]
first_three

[1, 'two', 3.0]

mi ejemplo 05

In [25]:
print(s)
primeros_cuatro=s[:4]
primeros_cuatro

['string=', 'hola', 'entero=', 1, 'numero punto flotante=', 2.333]


['string=', 'hola', 'entero=', 1]

In [26]:
# l[3:] is equivalent to l[3:len(l)].
print(l)
after_three = l[3:]
after_three

[1, 'two', 3.0, 4, 5.0, 'six']


[4, 5.0, 'six']

mi ejemplo 06

In [27]:
despues_del_cuarto = s[4:]
despues_del_cuarto


['numero punto flotante=', 2.333]

In [28]:
# There's also a third parameter, "step", which gets every Nth element.
l = ['a', 'b', 'c', 'd', 'e', 'f', 'g','h']
l[1:7:2]

['b', 'd', 'f']

mi ejemplo 07

In [29]:
s=[1,2,3,4,5,6,7,8,9,]
s[1::2]

[2, 4, 6, 8]

In [30]:
# This is a cute way to reverse a list.
l[::-1]

['h', 'g', 'f', 'e', 'd', 'c', 'b', 'a']

mi ejemplo 08

In [31]:
s[::-1]

[9, 8, 7, 6, 5, 4, 3, 2, 1]

In [32]:
# Lists can be grown efficiently (in O(1) amortized time).
l = [1, 2, 3, 4, 5]
print("Before:", l)
l.append('six')
print("After:", l)

Before: [1, 2, 3, 4, 5]
After: [1, 2, 3, 4, 5, 'six']


mi ejemplo 09

In [33]:
s=[11,12,13,14,15]
print("inicial:",s)
s.append("añadido por .append")
print("resultante:",s)

inicial: [11, 12, 13, 14, 15]
resultante: [11, 12, 13, 14, 15, 'añadido por .append']


In [34]:
# Comprehensions let us perform elementwise computations.
l = [1, 2, 3, 4, 5]
[x * 2 for x in l]

[2, 4, 6, 8, 10]

mi ejemplo 10

In [35]:
s=[11,12,13,14,15]
[x-10 for x in s]

[1, 2, 3, 4, 5]

## Review: Python Lists

- Zero-indexed sequence of arbitrary Python values.
- Slicing syntax: `l[start:stop:step]` copies elements at regular intervals from `start` to `stop`.
- Efficient (`O(1)`) appends and removes from end.
- Comprehension syntax: `[f(x) for x in l if cond(x)]`.

# Dictionaries

In [11]:
# Dictionaries are key-value mappings.
philosophers = {'David': 'Hume', 'Immanuel': 'Kant', 'Bertrand': 'Russell'}
philosophers

{'Bertrand': 'Russell', 'David': 'Hume', 'Immanuel': 'Kant'}

Mi ejemplo 11

In [12]:
ingenieros= {'Antony':' bedborf', 'Wallace': 'Fowler', 'Stephen': 'Timoshenko'}
ingenieros

{'Antony': ' bedborf', 'Stephen': 'Timoshenko', 'Wallace': 'Fowler'}

In [13]:
# Like lists, dictionaries are size-mutable.
philosophers['Ludwig'] = 'Wittgenstein'
philosophers

{'Bertrand': 'Russell',
 'David': 'Hume',
 'Immanuel': 'Kant',
 'Ludwig': 'Wittgenstein'}

mi ejemplo 12

In [8]:
ingenieros['James']='Gere'
ingenieros

{'Antony': ' bedborf',
 'James': 'Gere',
 'Stephen': 'Timoshenko',
 'Wallace': 'Fowler'}

In [ ]:
del philosophers['David']
philosophers

{'Bertrand': 'Russell', 'Immanuel': 'Kant', 'Ludwig': 'Wittgenstein'}

mi ejemplo 13

In [9]:
del ingenieros['Antony']
ingenieros

{'James': 'Gere', 'Stephen': 'Timoshenko', 'Wallace': 'Fowler'}

In [13]:
# No slicing.
philosophers['Bertrand':'Immanuel']

TypeError: ignored

mi ejemplo 14

In [14]:
ingenieros['Antony':'James']

TypeError: ignored

## Review: Python Dictionaries

- Unordered key-value mapping from (almost) arbitrary keys to arbitrary values.
- Efficient (`O(1)`) lookup, insertion, and deletion.
- No slicing (would require a notion of order).

<center><img src="images/pacino.gif" alt="Drawing" style="width: 100%;"/></center>


In [14]:
# Suppose we have some matrices...
a = [[1, 2, 3],
     [2, 3, 4],
     [5, 6, 7],
     [1, 1, 1]]

b = [[1, 2, 3, 4],
     [2, 3, 4, 5]]

mi ejemplo 15

In [15]:
s = [[10, 20, 30],
     [20, 30, 40],
     [50, 60, 70],
     [10, 10, 10]]

t = [[.1, .2, .3, .4],
     [.2, .3, .4, .5]]

In [16]:
def matmul(A, B):
    """Multiply matrix A by matrix B."""
    rows_out = len(A)
    cols_out = len(B[0])
    out = [[0 for col in range(cols_out)] for row in range(rows_out)]
    
    for i in range(rows_out):
        for j in range(cols_out):
            for k in range(len(B)):
                out[i][j] += A[i][k] * B[k][j]
    return out

<center><img src="images/gross.gif" alt="Drawing" style="width: 50%;"/></center>


In [17]:
%%time

matmul(a, b)

CPU times: user 48 µs, sys: 0 ns, total: 48 µs
Wall time: 52 µs


[[5, 8, 11, 14], [8, 13, 18, 23], [17, 28, 39, 50], [3, 5, 7, 9]]

mi ejemplo 16

In [18]:
%%time

matmul(s, t)

CPU times: user 36 µs, sys: 8 µs, total: 44 µs
Wall time: 47.9 µs


[[5.0, 8.0, 11.0, 14.0],
 [8.0, 13.0, 18.0, 23.0],
 [17.0, 28.0, 39.0, 50.0],
 [3.0, 5.0, 7.0, 9.0]]

In [19]:
import random
def random_matrix(m, n):
    out = []
    for row in range(m):
        out.append([random.random() for _ in range(n)])
    return out

randm = random_matrix(2, 3)
randm

[[0.8005438033716435, 0.8762641923260753, 0.8481820485559401],
 [0.25319568698113526, 0.8935232867138754, 0.18099273026720109]]

mi ejemplo 16.5

In [20]:
randm1 = random_matrix(2, 3)
randm1

[[0.5075848005553301, 0.5080035794714616, 0.04560522187743621],
 [0.42433194090581416, 0.5127688250925929, 0.8235069357424316]]

In [21]:
%%time
randa = random_matrix(600, 100)
randb = random_matrix(100, 600)
x = matmul(randa, randb)

CPU times: user 10.2 s, sys: 22.9 ms, total: 10.2 s
Wall time: 10.2 s


mi ejemplo 17

In [22]:
%%time
randa = random_matrix(6, 11)
randb = random_matrix(1, 6)
s = matmul(randa, randb)

CPU times: user 100 µs, sys: 6 µs, total: 106 µs
Wall time: 111 µs


In [23]:
# Maybe that's not that bad?  Let's try a simpler case.
def python_dot_product(xs, ys):
    return sum(x * y for x, y in zip(xs, ys))

In [24]:
%%fortran
subroutine fortran_dot_product(xs, ys, result)
    double precision, intent(in) :: xs(:)
    double precision, intent(in) :: ys(:)
    double precision, intent(out) :: result
    
    result = sum(xs * ys)
end

mi ejemplo 17.5

In [31]:
%%fortran
subroutine fortran_dot_product(ss, ts, result)
    double precision, intent(in) :: ss(:)
    double precision, intent(in) :: ts(:)
    double precision, intent(out) :: result
    
    result = sum(ss * ts)
end

In [25]:
list_data = [float(i) for i in range(100000)]
array_data = np.array(list_data)

mi ejemplo 19

In [26]:
list_data1 = [float(i) for i in range(900000)]
array_data1 = np.array(list_data1)

In [27]:
%%time
python_dot_product(list_data, list_data)

CPU times: user 9.28 ms, sys: 1.02 ms, total: 10.3 ms
Wall time: 10.2 ms


333328333350000.0

mi ejemplo 20

In [28]:
%%time
python_dot_product(list_data1, list_data1)

CPU times: user 84.3 ms, sys: 927 µs, total: 85.2 ms
Wall time: 86.7 ms


2.4299959499973837e+17

In [49]:
%%time
fortran_dot_product(array_data, array_data)

CPU times: user 264 µs, sys: 0 ns, total: 264 µs
Wall time: 274 µs


333328333350000.0

mi ejemplo 21

In [29]:
%%time
fortran_dot_product(array_data1, array_data1)

CPU times: user 1.92 ms, sys: 54 µs, total: 1.97 ms
Wall time: 2.27 ms


2.4299959499973837e+17

<center><img src="images/sloth.gif" alt="Drawing" style="width: 1080px;"/></center>


## Why is the Python Version so Much Slower?

In [38]:
# Dynamic typing.
def mul_elemwise(xs, ys):
    return [x * y for x, y in zip(xs, ys)]

mul_elemwise([1, 2, 3, 4], [1, 2 + 0j, 3.0, 'four'])
#[type(x) for x in _]

[1, (4+0j), 9.0, 'fourfourfourfour']

mi ejemplo 22

In [39]:
# Dynamic typing.
def mul_elemwise1(ss, ts):
    return [s * t for s, t in zip(ss, ts)]

mul_elemwise1([10, 20, 30, 40], [10, 2 + 0j, 3.0, 'ja'])
#[type(x) for x in _]

[100,
 (40+0j),
 90.0,
 'jajajajajajajajajajajajajajajajajajajajajajajajajajajajajajajajajajajajajajajaja']

In [40]:
# Interpretation overhead.
source_code = 'a + b * c'
bytecode = compile(source_code, '', 'eval')
import dis; dis.dis(bytecode)

  1           0 LOAD_NAME                0 (a)
              2 LOAD_NAME                1 (b)
              4 LOAD_NAME                2 (c)
              6 BINARY_MULTIPLY
              8 BINARY_ADD
             10 RETURN_VALUE


mi ejemplo 23

In [41]:
# Interpretation overhead.
source_code = 'j + s * t'
bytecode = compile(source_code, '', 'single')
import dis; dis.dis(bytecode)

  1           0 LOAD_NAME                0 (j)
              2 LOAD_NAME                1 (s)
              4 LOAD_NAME                2 (t)
              6 BINARY_MULTIPLY
              8 BINARY_ADD
             10 PRINT_EXPR
             12 LOAD_CONST               0 (None)
             14 RETURN_VALUE


## Why is the Python Version so Slow?
- Dynamic typing means that every single operation requires dispatching on the input type.
- Having an interpreter means that every instruction is fetched and dispatched at runtime.
- Other overheads:
  - Arbitrary-size integers.
  - Reference-counted garbage collection.

> This is the paradox that we have to work with when we're doing scientific or numerically-intensive Python. What makes Python fast for development -- this high-level, interpreted, and dynamically-typed aspect of the language -- is exactly what makes it slow for code execution.

- Jake VanderPlas, [*Losing Your Loops: Fast Numerical Computing with NumPy*](https://www.youtube.com/watch?v=EEUXKG97YRw)

# What Do We Do?

<center><img src="images/runaway.gif" alt="Drawing" style="width: 50%;"/></center>

<center><img src="images/thisisfine.gif" alt="Drawing" style="width: 1080px;"/></center>

- Python is slow for numerical computation because it performs dynamic dispatch on every operation we perform...

- ...but often, we just want to do the same thing over and over in a loop!

- If we don't need Python's dynamicism, we don't want to pay (much) for it.

- **Idea:** Dispatch **once per operation** instead of **once per element**.

In [48]:
import numpy as np

data = np.array([1, 2, 3, 4])
data

array([1, 2, 3, 4])

mi ejemplo 24

In [50]:
data1=np.array([10, 20, 30, 40])
data1

array([10, 20, 30, 40])

In [43]:
data + data

array([2, 4, 6, 8])

mi ejemplo 25

In [51]:
data1 + data1

array([20, 40, 60, 80])

In [44]:
%%time
# Naive dot product
(array_data * array_data).sum()

CPU times: user 746 µs, sys: 1.06 ms, total: 1.81 ms
Wall time: 3.5 ms


333328333350000.0

mi ejemplo 26

In [52]:
%%time
# Naive dot product
(array_data1 * array_data1).sum()

CPU times: user 3.08 ms, sys: 1.96 ms, total: 5.04 ms
Wall time: 13.1 ms


2.4299959500015e+17

In [45]:
%%time
# Built-in dot product.
array_data.dot(array_data)

CPU times: user 1.57 ms, sys: 38 µs, total: 1.61 ms
Wall time: 2.38 ms


333328333350000.0

mi ejempo 27

In [53]:
%%time
# Built-in dot product.
array_data1.dot(array_data1)

CPU times: user 1.63 ms, sys: 142 µs, total: 1.77 ms
Wall time: 7.65 ms


2.4299959500010298e+17

In [46]:
%%time
fortran_dot_product(array_data, array_data)

CPU times: user 216 µs, sys: 15 µs, total: 231 µs
Wall time: 241 µs


333328333350000.0

mi ejemplo 28

In [54]:
%%time
fortran_dot_product(array_data1, array_data1)

CPU times: user 1.7 ms, sys: 0 ns, total: 1.7 ms
Wall time: 2.03 ms


2.4299959499973837e+17

In [47]:
# Numpy won't allow us to write a string into an int array.
data[0] = "foo"

ValueError: ignored

In [55]:
# We also can't grow an array once it's created.
data.append(3)

AttributeError: ignored

In [56]:
# We **can** reshape an array though.
two_by_two = data.reshape(2, 2)
two_by_two

array([[1, 2],
       [3, 4]])

mi ejemplo 29

In [58]:
# We **can** reshape an array though.
dos_by_dos = data1.reshape(2, 2)
dos_by_dos

array([[10, 20],
       [30, 40]])

Numpy arrays are:

- Fixed-type

- Size-immutable

- Multi-dimensional

- Fast\*

\* If you use them correctly.

# What's in an Array?

In [59]:
arr = np.array([1, 2, 3, 4, 5, 6], dtype='int16').reshape(2, 3)
print("Array:\n", arr, sep='')
print("===========")
print("DType:", arr.dtype)
print("Shape:", arr.shape)
print("Strides:", arr.strides)
print("Data:", arr.data.tobytes())

Array:
[[1 2 3]
 [4 5 6]]
DType: int16
Shape: (2, 3)
Strides: (6, 2)
Data: b'\x01\x00\x02\x00\x03\x00\x04\x00\x05\x00\x06\x00'


mi ejempo 30

In [62]:
arr = np.array([10, 20, 30, 40, 50, 60], dtype='int16').reshape(6, 1)
print("Array:\n", arr, sep='')
print("===========")
print("DType:", arr.dtype)
print("Shape:", arr.shape)
print("Strides:", arr.strides)
print("Data:", arr.data.tobytes())

Array:
[[10]
 [20]
 [30]
 [40]
 [50]
 [60]]
DType: int16
Shape: (6, 1)
Strides: (2, 2)
Data: b'\n\x00\x14\x00\x1e\x00(\x002\x00<\x00'


# Core Operations

- Vectorized **ufuncs** for elementwise operations.
- Fancy indexing and masking for selection and filtering.
- Aggregations across axes.
- Broadcasting

# UFuncs

UFuncs (universal functions) are functions that operate elementwise on one or more arrays.

In [ ]:
data = np.arange(15).reshape(3, 5)
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

mi ejemplo 31

In [64]:
data1= np.arange(20).reshape(4, 5)
data1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
# Binary operators.
data * data

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196]])

mi ejemplo 32

In [65]:
data1 * data1

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361]])

In [ ]:
# Unary functions.
np.sqrt(data)

array([[ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ],
       [ 2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ],
       [ 3.16227766,  3.31662479,  3.46410162,  3.60555128,  3.74165739]])

mi ejemplo 33

In [66]:
np.sqrt(data1)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739],
       [3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894]])

In [ ]:
# Comparison operations
(data % 3) == 0

array([[ True, False, False,  True, False],
       [False,  True, False, False,  True],
       [False, False,  True, False, False]], dtype=bool)

mi ejemplo 34

In [72]:
(data1 % 1) == 0

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [73]:
data1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
# Boolean combinators.
((data % 2) == 0) & ((data % 3) == 0)

array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False]], dtype=bool)

mi ejemplo 35

In [74]:
((data1 % 5) == 0) & ((data1 % 2) == 0)

array([[ True, False, False, False, False],
       [False, False, False, False, False],
       [ True, False, False, False, False],
       [False, False, False, False, False]])

In [ ]:
# as of python 3.5, @ is matrix-multiply
data @ data.T

array([[ 30,  80, 130],
       [ 80, 255, 430],
       [130, 430, 730]])

mi ejemplo 36

In [75]:
data1 @ data1.T

array([[  30,   80,  130,  180],
       [  80,  255,  430,  605],
       [ 130,  430,  730, 1030],
       [ 180,  605, 1030, 1455]])

mi ejemplo 36

# UFuncs Review

- UFuncs provide efficient elementwise operations applied across one or more arrays.
- Arithmetic Operators (`+`, `*`, `/`)
- Comparisons (`==`, `>`, `!=`)
- Boolean Operators (`&`, `|`, `^`)
- Trigonometric Functions (`sin`, `cos`)
- Transcendental Functions (`exp`, `log`)

# Selections

We often want to perform an operation on just a subset of our data.

In [78]:
sines = np.sin(np.linspace(0, 3.14, 10))
cosines = np.cos(np.linspace(0, 3.14, 10))
sines

array([0.        , 0.34185385, 0.64251645, 0.86575984, 0.98468459,
       0.98496101, 0.8665558 , 0.64373604, 0.34335012, 0.00159265])

mi ejemplo 37

In [88]:
sines = np.sin(np.linspace(0, 3.14, 91))
cosines = np.cos(np.linspace(0, 3.14, 91))
sines

array([0.        , 0.03488181, 0.06972117, 0.10447567, 0.139103  ,
       0.17356104, 0.20780783, 0.2418017 , 0.27550127, 0.30886552,
       0.34185385, 0.3744261 , 0.40654264, 0.43816437, 0.4692528 ,
       0.4997701 , 0.52967913, 0.55894348, 0.58752753, 0.61539649,
       0.64251645, 0.66885439, 0.69437827, 0.71905701, 0.74286057,
       0.76576   , 0.7877274 , 0.80873606, 0.8287604 , 0.84777604,
       0.86575984, 0.88268992, 0.89854566, 0.91330778, 0.9269583 ,
       0.93948061, 0.95085946, 0.96108101, 0.97013283, 0.97800388,
       0.98468459, 0.99016683, 0.99444393, 0.99751068, 0.99936335,
       0.99999968, 0.9994189 , 0.99762172, 0.99461032, 0.99038838,
       0.98496101, 0.97833484, 0.97051793, 0.96151979, 0.95135138,
       0.94002506, 0.92755463, 0.91395526, 0.89924351, 0.88343727,
       0.8665558 , 0.84861963, 0.8296506 , 0.80967179, 0.78870752,
       0.7667833 , 0.74392583, 0.72016291, 0.69552348, 0.67003751,
       0.64373604, 0.61665107, 0.58881556, 0.5602634 , 0.53102

In [83]:
# Slicing works with the same semantics as Python lists.
sines[0]

0.0

mi ejemplo 38

In [89]:
sines[90]

0.0015926529164868282

In [85]:
sines[:3]  # First three elements  

array([0.        , 0.00159265])

mi ejemplo 39

In [96]:
sines[:46]

array([0.        , 0.03488181, 0.06972117, 0.10447567, 0.139103  ,
       0.17356104, 0.20780783, 0.2418017 , 0.27550127, 0.30886552,
       0.34185385, 0.3744261 , 0.40654264, 0.43816437, 0.4692528 ,
       0.4997701 , 0.52967913, 0.55894348, 0.58752753, 0.61539649,
       0.64251645, 0.66885439, 0.69437827, 0.71905701, 0.74286057,
       0.76576   , 0.7877274 , 0.80873606, 0.8287604 , 0.84777604,
       0.86575984, 0.88268992, 0.89854566, 0.91330778, 0.9269583 ,
       0.93948061, 0.95085946, 0.96108101, 0.97013283, 0.97800388,
       0.98468459, 0.99016683, 0.99444393, 0.99751068, 0.99936335,
       0.99999968])

In [ ]:
sines[5:]  # Elements from 5 on.

array([ 0.98496101,  0.8665558 ,  0.64373604,  0.34335012,  0.00159265])

mi ejemplo 40

In [98]:
sines[45:]

array([0.99999968, 0.9994189 , 0.99762172, 0.99461032, 0.99038838,
       0.98496101, 0.97833484, 0.97051793, 0.96151979, 0.95135138,
       0.94002506, 0.92755463, 0.91395526, 0.89924351, 0.88343727,
       0.8665558 , 0.84861963, 0.8296506 , 0.80967179, 0.78870752,
       0.7667833 , 0.74392583, 0.72016291, 0.69552348, 0.67003751,
       0.64373604, 0.61665107, 0.58881556, 0.5602634 , 0.53102934,
       0.50114896, 0.47065862, 0.43959544, 0.40799722, 0.37590243,
       0.34335012, 0.31037991, 0.27703194, 0.24334679, 0.20936545,
       0.1751293 , 0.14068   , 0.10605947, 0.07130986, 0.03647345,
       0.00159265])

In [ ]:
sines[::2]  # Every other element.

array([ 0.        ,  0.64251645,  0.98468459,  0.8665558 ,  0.34335012])

mi ejemplo 42

In [99]:
sines[::45] 

array([0.        , 0.99999968, 0.00159265])

In [ ]:
# More interesting: we can index with boolean arrays to filter by a predicate.
print("sines:\n", sines)
print("sines > 0.5:\n", sines > 0.5)
print("sines[sines > 0.5]:\n", sines[sines > 0.5])

sines:
 [ 0.          0.34185385  0.64251645  0.86575984  0.98468459  0.98496101
  0.8665558   0.64373604  0.34335012  0.00159265]
sines > 0.5:
 [False False  True  True  True  True  True  True False False]
sines[sines > 0.5]:
 [ 0.64251645  0.86575984  0.98468459  0.98496101  0.8665558   0.64373604]


mi ejemplo 43

In [100]:
print("sines:\n", sines)
print("sines > 0.5:\n", sines > 0.5)
print("sines[sines > 0.5]:\n", sines[sines > 0.5])

sines:
 [0.         0.03488181 0.06972117 0.10447567 0.139103   0.17356104
 0.20780783 0.2418017  0.27550127 0.30886552 0.34185385 0.3744261
 0.40654264 0.43816437 0.4692528  0.4997701  0.52967913 0.55894348
 0.58752753 0.61539649 0.64251645 0.66885439 0.69437827 0.71905701
 0.74286057 0.76576    0.7877274  0.80873606 0.8287604  0.84777604
 0.86575984 0.88268992 0.89854566 0.91330778 0.9269583  0.93948061
 0.95085946 0.96108101 0.97013283 0.97800388 0.98468459 0.99016683
 0.99444393 0.99751068 0.99936335 0.99999968 0.9994189  0.99762172
 0.99461032 0.99038838 0.98496101 0.97833484 0.97051793 0.96151979
 0.95135138 0.94002506 0.92755463 0.91395526 0.89924351 0.88343727
 0.8665558  0.84861963 0.8296506  0.80967179 0.78870752 0.7667833
 0.74392583 0.72016291 0.69552348 0.67003751 0.64373604 0.61665107
 0.58881556 0.5602634  0.53102934 0.50114896 0.47065862 0.43959544
 0.40799722 0.37590243 0.34335012 0.31037991 0.27703194 0.24334679
 0.20936545 0.1751293  0.14068    0.10605947 0.07130986 

In [ ]:
# We index with lists/arrays of integers to select values at those indices.
print(sines)
sines[[0, 4, 7]]

[ 0.          0.34185385  0.64251645  0.86575984  0.98468459  0.98496101
  0.8665558   0.64373604  0.34335012  0.00159265]


array([ 0.        ,  0.98468459,  0.64373604])

mi ejmeplo 44

In [103]:
print(sines)
sines[[0, 45, 90]]

[0.         0.03488181 0.06972117 0.10447567 0.139103   0.17356104
 0.20780783 0.2418017  0.27550127 0.30886552 0.34185385 0.3744261
 0.40654264 0.43816437 0.4692528  0.4997701  0.52967913 0.55894348
 0.58752753 0.61539649 0.64251645 0.66885439 0.69437827 0.71905701
 0.74286057 0.76576    0.7877274  0.80873606 0.8287604  0.84777604
 0.86575984 0.88268992 0.89854566 0.91330778 0.9269583  0.93948061
 0.95085946 0.96108101 0.97013283 0.97800388 0.98468459 0.99016683
 0.99444393 0.99751068 0.99936335 0.99999968 0.9994189  0.99762172
 0.99461032 0.99038838 0.98496101 0.97833484 0.97051793 0.96151979
 0.95135138 0.94002506 0.92755463 0.91395526 0.89924351 0.88343727
 0.8665558  0.84861963 0.8296506  0.80967179 0.78870752 0.7667833
 0.74392583 0.72016291 0.69552348 0.67003751 0.64373604 0.61665107
 0.58881556 0.5602634  0.53102934 0.50114896 0.47065862 0.43959544
 0.40799722 0.37590243 0.34335012 0.31037991 0.27703194 0.24334679
 0.20936545 0.1751293  0.14068    0.10605947 0.07130986 0.036473

array([0.        , 0.99999968, 0.00159265])

In [ ]:
# Index arrays are often used for sorting one or more arrays.
unsorted_data = np.array([1, 3, 2, 12, -1, 5, 2])

mi ejemplo 45

In [107]:
unsorted_data1 = np.array([10, 30, 20, 102, -10, 50, 20])
sort_indices1 = np.argsort(unsorted_data1)
sort_indices1

array([4, 0, 2, 6, 1, 5, 3])

In [109]:
sort_indices = np.argsort(unsorted_data)
sort_indices

array([4, 0, 2, 6, 1, 5, 3])

In [110]:
unsorted_data[sort_indices]

array([-1,  1,  2,  2,  3,  5, 12])

mi ejemplo 46

In [112]:
unsorted_data1[sort_indices1]

array([-10,  10,  20,  20,  30,  50, 102])

In [113]:
market_caps = np.array([12, 6, 10, 5, 6])  # Presumably in dollars?
assets = np.array(['A', 'B', 'C', 'D', 'E'])

In [114]:
# Sort assets by market cap by using the permutation that would sort market caps on ``assets``.
sort_by_mcap = np.argsort(market_caps)
assets[sort_by_mcap]

array(['D', 'B', 'E', 'C', 'A'], dtype='<U1')

mi ejemplo 47

In [117]:
market_caps1 = np.array([123, 63, 103, 53, 63])  # Presumably in dollars?
assets1= np.array(['Aa', 'Bb', 'Cc', 'Ds', 'Ee'])
sort_by_mcap1 = np.argsort(market_caps1)
assets1[sort_by_mcap1]

array(['Ds', 'Bb', 'Ee', 'Cc', 'Aa'], dtype='<U2')

In [118]:
# Indexers are also useful for aligning data.
print("Dates:\n", repr(event_dates))
print("Values:\n", repr(event_values))
print("Calendar:\n", repr(calendar))

Dates:
 array(['2017-01-06', '2017-01-07', '2017-01-08'], dtype='datetime64[D]')
Values:
 array([10, 15, 20])
Calendar:
 array(['2017-01-03', '2017-01-04', '2017-01-05', '2017-01-06',
       '2017-01-09', '2017-01-10', '2017-01-11', '2017-01-12',
       '2017-01-13', '2017-01-17', '2017-01-18', '2017-01-19',
       '2017-01-20', '2017-01-23', '2017-01-24', '2017-01-25',
       '2017-01-26', '2017-01-27', '2017-01-30', '2017-01-31',
       '2017-02-01'], dtype='datetime64[D]')


mi ejemplo 48

In [ ]:
print("Dates:\n", repr(event_dates))
print("Values:\n", repr(event_values))
print("Calendar:\n", repr(calendar))

In [ ]:
print("Raw Dates:", event_dates)
print("Indices:", calendar.searchsorted(event_dates))
print("Forward-Filled Dates:", calendar[calendar.searchsorted(event_dates)])

Raw Dates: ['2017-01-06' '2017-01-07' '2017-01-08']
Indices: [3 4 4]
Forward-Filled Dates: ['2017-01-06' '2017-01-09' '2017-01-09']


mi ejemplo 49

In [119]:
print("Raw Dates:", event_dates)
print("Indices:", calendar.searchsorted(event_dates))
print("Forward-Filled Dates:", calendar[calendar.searchsorted(event_dates)])

Raw Dates: ['2017-01-06' '2017-01-07' '2017-01-08']
Indices: [3 4 4]
Forward-Filled Dates: ['2017-01-06' '2017-01-09' '2017-01-09']


On multi-dimensional arrays, we can slice along each axis independently.

In [ ]:
data = np.arange(25).reshape(5, 5)
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

mi ejemplo 50

In [120]:
data1 = np.arange(16).reshape(4, 4)
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
data[:2, :2]  # First two rows and first two columns.

array([[0, 1],
       [5, 6]])

mi ejemplo 51

In [124]:
data1[:4, :2]

array([[ 0,  1],
       [ 5,  6],
       [10, 11],
       [15, 16]])

In [ ]:
data[:2, [0, -1]]  # First two rows, first and last columns.

array([[0, 4],
       [5, 9]])

mi ejemplo 52

In [125]:
data1[:4, [0, -1]]

array([[ 0,  4],
       [ 5,  9],
       [10, 14],
       [15, 19]])

In [ ]:
data[(data[:, 0] % 2) == 0]  # Rows where the first column is divisible by two.

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

mi ejemplo 53

In [127]:
data[(data[:, 0] % 4) == 0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

# Selections Review

- Indexing with an integer removes a dimension.
- Slicing operations work on Numpy arrays the same way they do on lists.
- Indexing with a boolean array filters to True locations.
- Indexing with an integer array selects indices along an axis.
- Multidimensional arrays can apply selections independently along different axes.

## Reductions

Functions that reduce an array to a scalar.

$Var(X) = \frac{1}{N}\sqrt{\sum_{i=1}^N (x_i - \bar{x})^2}$

In [128]:
def variance(x):
    return ((x - x.mean()) ** 2).sum() / len(x)

In [129]:
variance(np.random.standard_normal(1000))

0.9936056325237528

mi ejemplo 54

In [133]:
variance(np.random.standard_normal(2))

3.0074282292574375

- `sum()` and `mean()` are both **reductions**.

- In the simplest case, we use these to reduce an entire array into a single value...

In [ ]:
data = np.arange(30)
data.mean()

14.5

mi ejemplo 55

In [134]:
data = np.arange(85)
data.mean()

42.0

- ...but we can do more interesting things with multi-dimensional arrays.

In [ ]:
data = np.arange(30).reshape(3, 10)
data

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [135]:
data1=np.arange(30).reshape(6, 5)

In [ ]:
data.mean()

14.5

mi ejemplo 56

In [136]:
data1.mean()

14.5

In [138]:
data.mean(axis=0)

42.0

mi ejemplo 57

In [137]:
data1.mean(axis=0)

array([12.5, 13.5, 14.5, 15.5, 16.5])

In [ ]:
data.mean(axis=1)

array([  4.5,  14.5,  24.5])

mi ejemplo 58

In [ ]:
data.mean(axis=1)

## Reductions Review

- Reductions allow us to perform efficient aggregations over arrays.
- We can do aggregations over a single axis to collapse a single dimension.
- Many built-in reductions (`mean`, `sum`, `min`, `max`, `median`, ...).

# Broadcasting

In [139]:
row = np.array([1, 2, 3, 4])
column = np.array([[1], [2], [3]])
print("Row:\n", row, sep='')
print("Column:\n", column, sep='')

Row:
[1 2 3 4]
Column:
[[1]
 [2]
 [3]]


mi ejemplo 59

In [143]:
row1 = np.array([10, 20, 30, 40])
column1 = np.array([[10], [20], [30]])
print("Row1:\n", row, sep='')
print("Column1:\n", column, sep='')

Row1:
[1 2 3 4]
Column1:
[[1]
 [2]
 [3]]


In [142]:
row + column

array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])

mi ejemplo 60

In [144]:
row1 + column1

array([[20, 30, 40, 50],
       [30, 40, 50, 60],
       [40, 50, 60, 70]])

<center><img src="images/broadcasting.png" alt="Drawing" style="width: 60%;"/></center>

<h5>Source: http://www.scipy-lectures.org/_images/numpy_broadcasting.png</h5>

In [ ]:
# Broadcasting is particularly useful in conjunction with reductions.
print("Data:\n", data, sep='')
print("Mean:\n", data.mean(axis=0), sep='')
print("Data - Mean:\n", data - data.mean(axis=0), sep='')

Data:
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]
Mean:
[ 10.  11.  12.  13.  14.  15.  16.  17.  18.  19.]
Data - Mean:
[[-10. -10. -10. -10. -10. -10. -10. -10. -10. -10.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [ 10.  10.  10.  10.  10.  10.  10.  10.  10.  10.]]


mi ejemplo 61

In [145]:
print("Data:\n", data1, sep='')
print("Mean:\n", data1.mean(axis=0), sep='')
print("Data - Mean:\n", data1 - data1.mean(axis=0), sep='')

Data:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
Mean:
[12.5 13.5 14.5 15.5 16.5]
Data - Mean:
[[-12.5 -12.5 -12.5 -12.5 -12.5]
 [ -7.5  -7.5  -7.5  -7.5  -7.5]
 [ -2.5  -2.5  -2.5  -2.5  -2.5]
 [  2.5   2.5   2.5   2.5   2.5]
 [  7.5   7.5   7.5   7.5   7.5]
 [ 12.5  12.5  12.5  12.5  12.5]]


# Broadcasting Review

- Numpy operations can work on arrays of different dimensions as long as the arrays' shapes are still "compatible".
- Broadcasting works by "tiling" the smaller array along the missing dimension.
- The result of a broadcasted operation is always at least as large in each dimension as the largest array in that dimension.

# Numpy Review

- Numerical algorithms are slow in pure Python because the overhead dynamic dispatch dominates our runtime.

- Numpy solves this problem by:
  1. Imposing additional restrictions on the contents of arrays.
  2. Moving the inner loops of our algorithms into compiled C code.

- Using Numpy effectively often requires reworking an algorithms to use vectorized operations instead of for-loops, but the resulting operations are usually simpler, clearer, and faster than the pure Python equivalent.

<center><img src="images/unicorn.jpg" alt="Drawing" style="width: 75%;"/></center>

Numpy is great for many things, but...

- Sometimes our data is equipped with a natural set of **labels**:
  - Dates/Times
  - Stock Tickers
  - Field Names (e.g. Open/High/Low/Close)

- Sometimes we have **more than one type of data** that we want to keep grouped together.
  - Tables with a mix of real-valued and categorical data.

- Sometimes we have **missing** data, which we need to ignore, fill, or otherwise work around.

<center><img src="images/panda-wrangling.gif" alt="Drawing" style="width: 75%;"/></center>

<center><img src="images/pandas_logo.png" alt="Drawing" style="width: 75%;"/></center>


Pandas extends Numpy with more complex data structures:

- `Series`: 1-dimensional, homogenously-typed, labelled array.
- `DataFrame`: 2-dimensional, semi-homogenous, labelled table.

Pandas also provides many utilities for: 
- Input/Output
- Data Cleaning
- Rolling Algorithms
- Plotting

# Selection in Pandas

In [147]:
s = pd.Series(index=['a', 'b', 'c', 'd', 'e'], data=[1, 2, 3, 4, 5])
s

a    1
b    2
c    3
d    4
e    5
dtype: int64

mi ejemplo 62

In [148]:
si = pd.Series(index=['aA', 'bB', 'cC', 'dD', 'eE'], data=[10, 20, 30, 40, 50])
si

aA    10
bB    20
cC    30
dD    40
eE    50
dtype: int64

In [ ]:
# There are two pieces to a Series: the index and the values.
print("The index is:", s.index)
print("The values are:", s.values)

The index is: Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
The values are: [1 2 3 4 5]


MI EJEMPLO 63

In [149]:
print("The index is:", si.index)
print("The values are:", si.values)

The index is: Index(['aA', 'bB', 'cC', 'dD', 'eE'], dtype='object')
The values are: [10 20 30 40 50]


In [ ]:
# We can look up values out of a Series by position...
s.iloc[0]

1

mi ejemplo 64

In [150]:
si.iloc[0]

10

In [ ]:
# ... or by label.
s.loc['a']

1

mi ejemplo 65

In [151]:
si.loc['aA']

10

In [152]:
# Slicing works as expected...
s.iloc[:2]

1

MI EJEMPLO 66

In [155]:
si.iloc[:4]

aA    10
bB    20
cC    30
dD    40
dtype: int64

In [153]:
# ...but it works with labels too!
s.loc[:'c']

a    1
b    2
c    3
dtype: int64

mi ejemplo 67

In [157]:
si.loc[:'cC']

aA    10
bB    20
cC    30
dtype: int64

In [ ]:
# Fancy indexing works the same as in numpy.
s.iloc[[0, -1]]

a    1
e    5
dtype: int64

MI EJEMPLO 68

In [158]:
s.iloc[[0, -1]]

a    1
e    5
dtype: int64

In [ ]:
# As does boolean masking.
s.loc[s > 2]

c    3
d    4
e    5
dtype: int64

mi ejemplo 69

In [162]:
si.loc[si > 20]

cC    30
dD    40
eE    50
dtype: int64

In [ ]:
# Element-wise operations are aligned by index.
other_s = pd.Series({'a': 10.0, 'c': 20.0, 'd': 30.0, 'z': 40.0})
other_s

a    10.0
c    20.0
d    30.0
z    40.0
dtype: float64

mi ejemplo 70

In [164]:
other_si = pd.Series({'aA': 10.0, 'cB': 20.0, 'dD': 30.0, 'zZ': 40.0})
other_si

aA    10.0
cB    20.0
dD    30.0
zZ    40.0
dtype: float64

In [ ]:
s + other_s

a    11.0
b     NaN
c    23.0
d    34.0
e     NaN
z     NaN
dtype: float64

MI EJEMPLO 71

In [ ]:
si + other_si

In [ ]:
# We can fill in missing values with fillna().
(s + other_s).fillna(0.0)

a    11.0
b     0.0
c    23.0
d    34.0
e     0.0
z     0.0
dtype: float64

mi ejemplo 72

In [165]:
(si + other_si).fillna(900.0)

aA     20.0
bB    900.0
cB    900.0
cC    900.0
dD     70.0
eE    900.0
zZ    900.0
dtype: float64

In [169]:
# Most real datasets are read in from an external file format.
aapl = pd.read_csv('AAPL.csv', parse_dates=['Date'], index_col='Date')
aapl.head()

FileNotFoundError: ignored

In [170]:
# Slicing generalizes to two dimensions as you'd expect:
aapl.iloc[:2, :2]

NameError: ignored

In [171]:
aapl.loc[pd.Timestamp('2010-02-01'):pd.Timestamp('2010-02-04'), ['Close', 'Volume']]

NameError: ignored

# Rolling Operations

<center><img src="images/rolling.gif" alt="Drawing" style="width: 75%;"/></center>

In [172]:
aapl.rolling(5)[['Close', 'Adj Close']].mean().plot();

NameError: ignored

In [173]:
# Drop `Volume`, since it's way bigger than everything else.
aapl.drop('Volume', axis=1).resample('2W').max().plot();

NameError: ignored

In [174]:
# 30-day rolling exponentially-weighted stddev of returns.
aapl['Close'].pct_change().ewm(span=30).std().plot();

NameError: ignored

# "Real World" Data

In [175]:
from demos.avocados import read_avocadata

avocados = read_avocadata('2014', '2016')
avocados.head()

ModuleNotFoundError: ignored

In [176]:
# Unlike numpy arrays, pandas DataFrames can have a different dtype for each column.
avocados.dtypes

NameError: ignored

In [177]:
# What's the regional average price of a HASS avocado every day?
hass = avocados[avocados.Variety == 'HASS']
hass.groupby(['Date', 'Region'])['Weighted Avg Price'].mean().unstack().ffill().plot();

NameError: ignored

In [178]:
def _organic_spread(group):

    if len(group.columns) != 2:
        return pd.Series(index=group.index, data=0.0)
    
    is_organic = group.columns.get_level_values('Organic').values.astype(bool)
    organics = group.loc[:, is_organic].squeeze()
    non_organics = group.loc[:, ~is_organic].squeeze()
    diff = organics - non_organics
    return diff

def organic_spread_by_region(df):
    """What's the difference between the price of an organic 
    and non-organic avocado within each region?
    """
    return (
        df
        .set_index(['Date', 'Region', 'Organic'])
         ['Weighted Avg Price']
        .unstack(level=['Region', 'Organic'])
        .ffill()
        .groupby(level='Region', axis=1)
        .apply(_organic_spread)
    )

In [179]:
organic_spread_by_region(hass).plot();
plt.gca().set_title("Daily Regional Organic Spread");
plt.legend(bbox_to_anchor=(1, 1));

NameError: ignored

In [180]:
spread_correlation = organic_spread_by_region(hass).corr()
spread_correlation

NameError: ignored

In [181]:
import seaborn as sns
grid = sns.clustermap(spread_correlation, annot=True)
fig = grid.fig
axes = fig.axes
ax = axes[2]
ax.set_xticklabels(ax.get_xticklabels(), rotation=45);

NameError: ignored

# Pandas Review

- Pandas extends numpy with more complex datastructures and algorithms.
- If you understand numpy, you understand 90% of pandas.
- `groupby`, `set_index`, and `unstack` are powerful tools for working with categorical data.
- Avocado prices are surprisingly interesting :)

# Thanks!